---
cluster_name: Kubernetes Cluster
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.10.19.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 1
    cpu: 1
    memory: 2048
software:
  box: debian/bullseye64
  calico: 3.28.1
  kubernetes: 1.30.0-*
  k9s: v0.32.5
  helm: v3.16.1
